# Generated by Django 4.2.1 on 2023-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_compamy_company_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='method_permissions',
            field=models.CharField(choices=[('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('GET', 'GET'), ('POST', 'POST')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
