# Generated by Django 4.2.1 on 2023-06-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_groups_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiongroup',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managing_group_set', to='hr.positiongroup'),
        ),
    ]
