# Generated by Django 4.2.1 on 2023-06-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_positiongroup_managed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiongroup',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managing_group_set', to='hr.positiongroup'),
        ),
    ]
