# Generated by Django 4.2.1 on 2023-06-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positiongroup',
            name='method_permissions',
        ),
    ]
