# Generated by Django 4.2.1 on 2023-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_positiongroup_method_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='method_permissions',
            field=models.ManyToManyField(blank=True, to='hr.methodsmap'),
        ),
    ]
