# Generated by Django 4.2.1 on 2023-06-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_positiongroup_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiongroup',
            name='action',
            field=models.ManyToManyField(related_name='actoin_position_set', to='hr.action'),
        ),
    ]
