# Generated by Django 4.2.1 on 2023-06-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_compamy_company_alter_employee_options_and_more'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='hr.employee'),
            preserve_default=False,
        ),
    ]
